# Generated by Django 3.1 on 2020-08-14 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20200814_1626'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='day_created',
            new_name='date_created',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='day_created',
            new_name='date_created',
        ),
    ]
